import ProjectDescription
let config = Config(
    generationOptions: [
        .organizationName("Varun Santhanam"),
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors,
    ]
)
